---
- name: install | Ensure directories exists
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ openvpn_server_root_path }}/config"
    - "{{ openvpn_server_compose_path }}"

- name: install | template docker-compose.yml
  template:
    src: ovpn_compose.yaml.j2
    dest: "{{ openvpn_server_compose_path }}/docker-compose.yml"
    mode: 755
  notify: restart-ovpn

- name: install | template fw-rules.sh.j2
  template:
    src: fw-rules.sh.j2
    dest: "{{ openvpn_server_fw_rules_sh_path }}"
    mode: 755
  notify: restart-ovpn

- name: install | ensure file exists
  copy:
    content: ""
    dest: "{{ openvpn_server_conf_path }}"
    force: false
  notify: restart-ovpn

- name: install | Deploy Docker Compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ openvpn_server_compose_path }}"
    state: present
