---
- name: install | Ensure project directory exists
  file:
    path: "{{ openvpn_server_compose_path }}"
    state: directory
    mode: '0755'

- name: install | template docker-compose.yml
  template:
    src: ovpn_compose.yaml.j2
    dest: "{{ openvpn_server_compose_path }}/docker-compose.yml"
    mode: 755

- name: install | template fw-rules.sh.j2
  template:
    src: fw-rules.sh.j2
    dest: "{{ openvpn_server_fw_rules_sh_path }}"
    mode: 755

- name: install | ensure file exists
  copy:
    content: ""
    dest: "{{ openvpn_server_conf_path }}"
    force: false
