---
- name: Deploy docker images
  include_tasks: docker_image.yml
  loop_control:
     loop_var: openvpn_client_docker
  with_items: "{{ openvpn_client_dockers }}"
  when: openvpn_client_dockers is defined  